[package]
name = "xgboost_udf_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "34.0.0"
tokio = { version = "1.35.0", features = ["full"] }
xgboost = "0.1.4"

